# Disable the Gradle daemon for Continuous Integration servers as correctness 
# is usually a priority over speed in CI environments. Using a fresh 
# runtime for each build is more reliable since the runtime is completely 
# isolated from any previous builds. 

variables:
   GRADLE_OPTS: "-Dorg.gradle.daemon=false" 
stages:
  - build
  - test
  - .post

build:
   stage: build 
   script:
    - cd backend/radify_be
    - .\gradlew assemble 
test:
   stage: test
   script:
     - cd backend/radify_be
     - .\gradlew test

sonarqube:
   stage: test
   script:
      - cd backend/radify_be
      - .\gradlew sonarqube

deploy:
    stage: deploy
    script:
        - cd backend/radify_be
        - docker compose up -d --build
