version: '3'

services:
  docker-mysql:
    image: mysql:latest
    container_name: mysqlcontainer
    environment:
      - MYSQL_ROOT_PASSWORD=R@d!0252
      - MYSQL_DATABASE=radify
    ports:
      - "3307:3306"

  backend:
    image: backendimage:latest
    container_name: backend-container
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/radify?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    depends_on:
      - docker-mysql

  frontend:
    image: frontendimage:latest
    container_name: frontend-container
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend